### ISSUE TITLE
Change to popup in Firefox

### ISSUE THREAD

**Issue by abel-gerard** [Hokkaydo/MoodleCustomizer#1]
**What's the problem?**
Hi, as you may know, to activate/deactivate the extension you have to click on "KeepAlive" inside the popup. However, I find it counterintuitive to click on the name of the button to activate the extension instead of clicking directly on the button's image.

**What would you like**
I would like for the user to be able to click on the image representing the extension status to activate/deactivate the extension (maybe also removing the old way of interacting with the extension by clicking on the text).

**Comment by Hokkaydo** [comment]
It will be updated in the next release.
Thanks for pointing it out!

**Comment by tdaron** [comment]
Fixed in #2 new menu.
